- name: Configuring Go Lang
  hosts: dispatch
  become: yes
  tasks:
  - name: Installing Go Lang
    ansible.builtin.dnf:
      name: golang
      state: present
  
  - name: creating user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"

  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creat an app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Remove Zip file
    ansible.builtin.file:
      path: /tmp/dispatch.zip
      state: absent

  - name: Download application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
      dest: /tmp/dispatch.zip
  
  - name: removing code
    ansible.builtin.command: rm -rf /app/*

  - name: unzipping code
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: yes
  
  - name: Initialize go module
    ansible.builtin.command: go mod init dispatch
    args:
      chdir: /app

  - name: Download go dependencies
    ansible.builtin.command: go get
    args:
      chdir: /app

  - name: Build go application
    ansible.builtin.command: go build
    args:
      chdir: /app

  
  - name: Copying service file
    ansible.builtin.copy:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service

  - name: Daemon reload
    ansible.builtin.systemd:
      daemon_reload: yes
        
  - name: start dispatch
    ansible.builtin.service:
      name: dispatch
      state: restarted
      enabled: yes

