- name: Configuring Payment
  hosts: payment
  become: yes
  tasks:
  - name: installing python3
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - python3
    - gcc
    - python3-devel
  
  - name: creating user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"

  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creat an app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Remove Zip file
    ansible.builtin.file:
      path: /tmp/payment.zip
      state: absent

  - name: Download application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip
  
  - name: removing code
    ansible.builtin.command: rm -rf /app/*

  - name: unzipping code
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: Installing dependencies
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app
  
  - name: Copying payment service
    ansible.builtin.template:
      src: payment.repo
      dest: /etc/systemd/system/payment.service
  
  - name: Daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start shipping service
    ansible.builtin.service:
      name: payment
      state: restarted
      enabled: yes