- name: creating redis file
  hosts: redis
  become: yes
  tasks:
  - name: disable redis 
    ansible.builtin.command: dnf module disable redis -y
  - name: enable redis 7
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: installing redis
    ansible.builtin.dnf:
      name: redis
      state: present
  
  - name: replace
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: replace
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: 'protected-mode no'
  
  - name: Enable and start
    ansible.builtin.service:
      name: redis
      state: restarted
      enabled: yes
