- name: configuring the shipping service
  hosts: shipping
  become: yes
  tasks:
  - name: installing maven
    ansible.builtin.dnf:
      name: maven
      state: present

  - name: creating user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"

  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creat an app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Remove Zip file
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent

  - name: Download application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip
  
  - name: removing code
    ansible.builtin.command: rm -rf /app/*

  - name: unzipping code
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: installing dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

#here is where we want to install dependencies and move directories

  - name: moving between directories
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app
  
  - name: Copying service file
    ansible.builtin.template:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service
  
  - name: Install mysql
    ansible.builtin.dnf:
      name: mysql
      state: present
  
  - name: Daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Ensure Python MySQL driver is installed
    ansible.builtin.pip:
      name: PyMySQL
      executable: pip3

  - name: Load schema database
    community.mysql.mysql_db:
      name: shipping
      state: import
      login_host: "{{ MYSQL_HOST }}"
      login_password: ExpenseApp@1
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

  - name: start shipping service
    ansible.builtin.service:
      name: shipping
      state: restarted
      enabled: yes