- name: creating user file
  hosts: user
  become: yes
  tasks:
  - name: disabling nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enabling nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: creating user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"

  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creat an app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Remove Zip file
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent

  - name: Download application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip
  
  - name: removing code
    ansible.builtin.command: rm -rf /app/*

  - name: unzipping code
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
  
  - name: installing dependencies
    community.general.npm:
      path: /app
  
  - name: copy user service
    ansible.builtin.template:
      src: user.service
      dest: /etc/systemd/system/user.service
  
  - name: Daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: yes
        
  - name: start user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes




    
    